bab:
  draft:
    nomor: 0
    judul: "Draft"
  dasar:
    nomor: 1
    judul: "Pengantar"
  jump_loop:  
    nomor: 2
    judul: "Percabangan & Perulangan"
  arr_str:  
    nomor: 3
    judul: "Array & String"
  fungsi:  
    nomor: 4
    judul: "Fungsi"
  ptr_ref:  
    nomor: 5
    judul: "Pointer & Referensi"
  file:  
    nomor: 6
    judul: "Operasi File"
  struct:  
    nomor: 7
    judul: "Struct"
  union:  
    nomor: 8
    judul: "Union"
  typedef:  
    nomor: 9
    judul: "Typedef"
  prepro:  
    nomor: 10
    judul: "Preprosesor"
  memori:  
    nomor: 11
    judul: "Manajemen Memori"
  penutup:  
    nomor: 12
    judul: "Penutup"
