-
  nama: "Golang"
  desc: "Dasar Pemrograman Golang"
  url : "https://dasarpemrogramangolang.novalagung.com/"
  penulis: Noval Agung Prayogo
  link-penulis: "https://novalagung.com"
-
  nama: "Java"
  desc: "Tutorial Belajar Bahasa Pemrograman Java Online Indonesia"
  url : "https://www.okedroid.com/p/belajar-java.html"
  penulis: Fathur Rahman 
  link-penulis: "https://www.okedroid.com"
-
  nama: "PHP"
  desc: "Tutorial PHP Bahasa Indonesia"
  url : "https://www.lautankode.com/tutorial-php-bahasa-indonesia/"
  penulis: Lautan Kode
  link-penulis: "https://www.lautankode.com/"
- nama: "Python"
  desc: "Open Source Indonesian Python Programming Tutorial Site"
  url: "https://belajarpython.com/tutorial/apa-itu-python"
  penulis: belajarpythoncom
  link-penulis: "https://github.com/belajarpythoncom"
