bab:
  pertama:
    nomor: 1
    judul: Pertemuan 1
  kedua:
    nomor: 2
    judul: Pertemuan 2
  ketiga:
    nomor: 3
    judul: Pertemuan 3
  keempat:
    nomor: 4
    judul: Pertemuan 4
  kelima:
    nomor: 5
    judul: Pertemuan 5